### ISSUE TITLE
Make eva send random issue to meta-x on random interval

### ISSUE THREAD

**Issue by hargup** [metakgp/eva#4]
The issue will probably grab someone's attention prompting them to work on it. The random interval should be in order of days.

**Comment by vivekiitkgp** [comment]
Good idea. I was thinking on similar lines:

* Have a command to ask @eva to fetch a random issue (possibly with tags). So when a new person asks for a task, one can quickly fetch a couple of issues.
* Random prompts like: *Currently 8 issues and 2 pull requests are pending.*, *Most backlogged project is Blah*, and of course what you suggested.

**Comment by thealphadollar** [comment]
I'll be working on this in sometime.

If anyone has any lead, please put in :)
